name: Run Music Finder

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Game Catalog
        run: |
          pip3 install -U virtualenv
          python3 -m virtualenv venv
          source venv/bin/activate
          pip3 install -U -r requirements.txt
          python3 -m games -k ${{ secrets.APP_KEY }}
          deactivate
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./app
